name: remove_background
on: 
  workflow_dispatch:
    inputs:
      toProcess: 
        description: 'Zu verarbeitende Datei'
        required: true
        default: './not_processed/FILENAME'
jobs:
  my-job:
    runs-on: ubuntu-latest    
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: setup
        run: ./setup-rembg.sh
      - name: upscale
        run:  echo "$toProcess \n"; python3 ./run.py $toProcess
      - uses: stefanzweifel/git-auto-commit-action@v5