name: remove_background
on: 
  workflow_dispatch:
    inputs:
      to_process: 
        description: 'Zu verarbeitende Datei'
        required: true
        default: './not_processed/FILENAME'
jobs:
  remove-background-job:
    runs-on: ubuntu-latest    
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: set-permission
        run: git update-index --chmod=+x ./setup-rembg.sh
      - name: setup
        run: ./setup-rembg.sh
      - name: run_python
        run:  python3 ./run.py ${{ github.event.inputs.to_process }}
      - uses: stefanzweifel/git-auto-commit-action@v5