name: hello-world
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest    

    steps:
      - uses: actions/checkout@v4
      - name: check path
        run: ls 

      - name: setup-dependencies 
        run:  ./setup.sh
      - name: upscale
        run: python3 ./upscale.py ./astronaut.png
      - name: config user name  
        run: git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}" 
      - name: config user email 
        run: git config --global user.email "username@users.noreply.github.com"
      - name: git commit   
        run: git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
      - name: git push   
        run: git push
