name: hello-world
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest    

    steps:
      - uses: actions/checkout@v4
      - name: check path
        run: ls 

      - name: setup-dependencies 
        run:  ./setup.sh
      - name: upscale
        run: python3 ./upscale.py ./astronaut.png
      - uses: stefanzweifel/git-auto-commit-action@v5
