name: hello-world
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest    

    steps:
      - uses: actions/checkout@v4
        with:
          path: main
      - name: setup-dependencies 
        run: ./main/setup.sh
      - name: upscale
        run: python3 upscale-param.py astronaut.py
      - name: commit changes 
        run: 
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "username@users.noreply.github.com"
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push