name: upscale
on: 
  workflow_dispatch:
    inputs:
      to_process: 
        description: 'Zu verarbeitende Datei'
        required: true
        default: './not_processed/FILENAME'
jobs:
  my-job:
    runs-on: ubuntu-latest    
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: setup-permissions
        run: git update-index --chmod=+x ./setup-upscale.sh
      - name: setup-dependencies 
        run:  ./setup-upscale.sh
      - name: upscale
        run: python3 ./upscale.py   ${{ github.event.inputs.to_process }}
      - uses: stefanzweifel/git-auto-commit-action@v5
